/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void toStringTest(){
        Linkedliist ll =new Linkedliist();
        ll.add(5);
        ll.add(1);
        ll.add(2);
        ll.add(7);
        assertEquals("{ 5 } -> { 1 } -> { 2 } -> { 7 } -> NULL",ll.toString());
    }
    @Test public void insertTest(){
        Linkedliist ll =new Linkedliist();
        ll.add(5);
        ll.add(1);
        ll.add(2);
        ll.add(7);
        ll.insert(4);
        assertEquals("{ 4 } -> { 5 } -> { 1 } -> { 2 } -> { 7 } -> NULL",ll.toString());
    }
    @Test public void includeTest(){
        Linkedliist ll =new Linkedliist();
        ll.add(5);
        ll.add(1);
        ll.add(2);
        ll.add(7);
        ll.includes(4);
        assertEquals(false,ll.includes(4));
    }
    @Test public void append(){
        Linkedliist ll =new Linkedliist();
        ll.append(5);
        ll.append(1);
        ll.append(2);
        ll.append(7);
        assertEquals("{ 5 } -> { 1 } -> { 2 } -> { 7 } -> NULL",ll.toString());
    }
    @Test public void inserBeforTest(){
        Linkedliist ll =new Linkedliist();
        ll.append(5);
        ll.append(1);
        ll.append(2);
        ll.append(7);
        ll.insertBefore(1,9);
        assertEquals("{ 5 } -> { 9 } -> { 1 } -> { 2 } -> { 7 } -> NULL",ll.toString());
    }
    @Test public void insertAfterTest(){
        Linkedliist ll =new Linkedliist();
        ll.append(5);
        ll.append(1);
        ll.append(2);
        ll.append(7);
        ll.insertAfter(1,9);
        assertEquals("{ 5 } -> { 1 } -> { 9 } -> { 2 } -> { 7 } -> NULL",ll.toString());
    }

    @Test public void kthValueTest(){
        Linkedliist ll =new Linkedliist();
        ll.append(5);
        ll.append(1);
        ll.append(2);
        ll.append(7);
        ll.kthValue(1);
        assertEquals(2,ll.kthValue(1));
    }
}
