import java.util.LinkedList;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // insert code challenge 5
        System.out.println("// insert code challenge 5-----------");
        Linkedliist ll =new Linkedliist();
        ll.add(5);
        ll.add(1);
        ll.add(2);
        ll.add(7);
        ll.insert(4);
        Node current = ll.head;
//        System.out.println(current.value);
        while(current != null){
            System.out.println(current.value);
            current = current.next;
        }
//        System.out.println(current);

        // includes code challenge 5
        System.out.println("// includes code challenge 5-----------");
        ll.includes(5);
        System.out.println(ll.includes(7));
        // to string code challenge 1
        System.out.println(" // to string code challenge 5--------");
        System.out.println(ll.toString());

        // append  code challenge 6
        System.out.println(" // append code challenge 6--------");
        ll.append(9);
        ll.append(10);
        System.out.println(ll);
        // Insert Before  code challenge 6
        System.out.println("// Insert Before  code challenge 6-------");
        ll.insertBefore(4,9);
        System.out.println(ll);
        // Insert After  code challenge 6
        System.out.println(" // Insert After  code challenge 6 -----------");
        ll.insertAfter(4,9);
        System.out.println(ll);

        // Insert After  code challenge 7
        System.out.println(" // kthValue  code challenge 7");
        System.out.println(ll.kthValue(2));

        // reverse LinkedLis  code challenge 9
        System.out.println("reverseLinkedLis code challenge 9 ");
        System.out.println(ll.reverseLinkedList(ll));


    }

}
